:toc: macro
:toclevels: 5
:figure-caption!:

= Dotfiles

[link=https://circleci.com/gh/bkuhlmann/dotfiles]
image::https://circleci.com/gh/bkuhlmann/dotfiles.svg?style=svg[Circle CI Status]

These are shell scripts for applying default settings to UNIX-based operating systems. These are a
collection of useful shortcuts, performance augmentation, and advanced practices that, even if you
don't apply to your own dotfiles, should be educational for improving your own practices.

By default, these are set to my preferences (namely for macOS) but you can change them to your
liking by editing any of the `.tt` template files in the `home_files` directory. Read on to learn
more.

toc::[]

== Features

* Configures link:https://github.com/amazing-print/amazing_print[Amazing Print] (`.aprc`).
* Configures Bash (`.config/bash`, `.bashrc`, `.bash_profile`, and `.inputrc`).
* Configures link:http://bash-completion.alioth.debian.org[Bash Completion].
* Configures link:http://ctags.sourceforge.net[CTags] (`.ctags`).
* Configures link:https://direnv.net[direnv].
* Configures link:https://www.docker.com[Docker].
* Configures link:https://the.exa.website[Exa].
* Configures link:https://github.com/tako8ki/frum[Frum].
* Configures link:https://git-scm.com[Git] (`.config/git`).
* Configures link:https://www.gnupg.org[GPG].
* Configures `.hushlogin`.
* Configures link:https://nodejs.org[Node.js].
* Configures link:https://www.npmjs.org[NPM] (`.npmrc`).
* Configures link:https://www.postgresql.org[PostgreSQL] (`.psqlrc`).
* Configures link:https://voormedia.github.io/rails-erd[Rails ERD] (`.erdconfig`).
* Configures link:https://rspec.info[RSpec] (`.rspec`).
* Configures link:https://www.ruby-lang.org[Ruby] (`.ruby-version` and `.irbrc`).
* Configures link:http://bashdb.sourceforge.net/ruby-debug.html[Ruby Debugger] (`.rdebugrc`).
* Configures link:https://rubygems.org[Ruby Gems] (`.gemrc`).
* Configures link:https://github.com/bbatsov/rubocop[Rubocop] (`.rubocop.yml`).
* Configures link:https://www.rust-lang.org[Rust].
* Configures link:https://github.com/ggreer/the_silver_searcher[Silver Surfer] (`.agignore`).
* Configures link:https://www.sublimetext.com[Sublime Text].
* Configures link:https://www.vim.org[Vim] (`.vimrc`).
* Configures link:https://www.terraform.io[Terraform].
* Configures link:https://github.com/ajeetdsouza/zoxide[Zoxide].


== Requirements

. link:https://www.alchemists.io/projects/mac_os-config[macOS Configuration]

== Setup

To install, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/dotfiles.git
cd dotfiles
----

== Usage

[source,bash]
----
cd dotfiles
bin/run
----

Executing the `bin/run` script will present the following options:

....
s: Show managed dotfiles.
i: Install dotfiles (existing files are skipped).
l: Link dotfiles to this project (interactive per file, excludes: env.sh and .gitconfig).
c: Check for differences between $HOME files and this project's files.
d: Delete dotfiles (interactive per file, excludes: env.sh and .gitconfig).
q: Quit/Exit.
....

The options prompt can be skipped by passing the desired option directly to the `bin/run` script.
For example, executing `bin/run s` will show all managed dotfiles by this project.

After install, the following files will require manual updating:

* `.bash/env.sh`: Add secret/machine-specific environment settings (if any).
* `.gitconfig`: Uncomment the name, email, and token lines within the `[user]` and `[github]`
  sections to replace with your own details.


## Install
brew install bash
direnv
asciinema - record terminal
exa
postgres
redis
the_silver_searcher
npm
zoxide
chruby
ruby-install
bat
fd - find file
