#! /usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

source "$HOME/.config/git/hooks/extensions/support.sh"
source "$HOME/.config/git/hooks/extensions/java_script.sh"
source "$HOME/.config/git/hooks/extensions/ruby.sh"
source "$HOME/.config/git/hooks/extensions/dead_end.sh"

# java_script_alert
# java_script_console
# java_script_debugger
# ruby_debug
# ruby_dead_end
# minitest_focus
